"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
#import firebase_admin as fbs
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hrcy38i#-oze^q+rtu_af0djh0kkfek^i#-tnzrup#c4n)9288'
#SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework.authtoken',                                                                   
    'rest_framework_simplejwt', 
    'rest_framework',
    'corsheaders',                                                                     
    'djoser',
    'authapi',
    'based',       
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

# Use Django's standard `django.contrib.auth` permissions,
# or allow read-only access for unauthenticated users.
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=45),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
}


DJOSER = {
    'LOGIN_FIELD':"email",
    'USER_CREATE_PASSWORD_RETYPE' : True,
    'USERNAME_RESET_CONFIRM_URL': '/username/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL': '/activate/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': True,
    'SEND_CONFIRMATION_EMAIL': True,
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION': True,
    'PASSWORD_RESET_CONFIRM_RETYPE_URL': '/password-reset/{uid}/{token}',
    'PASSWORD_RESET_CONFIRM_URL': '/password/reset/confirm/{uid}/{token}',
    'SET_PASSWORD_RETYPE':True,
    'PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND': True,
    'TOKEN_MODEL': None,
    'SERIALIZERS':{
        'user_create': 'based.serializers.UserCreateSerializer',
        'user': 'based.serializers.UserCreateSerializer',
        'user_delete': 'djoser.serializers.UserDeleteSerializer',
    }
}

# cred = fbs.credentials.Certificate(os.path.join(BASE_DIR, "path/to/firebase_credentials.json"))
# fbs.initialize_app(cred)

ROOT_URLCONF = 'src.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'src.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Database
# if want use postgresql change = django.db.backends.postgresql, use mysql change = django.db.backends.mysql
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'masteruser',
        'PASSWORD': '12345678',
        'HOST': 'w3-django-project.cdxmgq9zqqlr.us-east-1.rds.amazonaws.com',
        'PORT': '5432'
    }
}

'''

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


'''
# AWS S3 settings
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'

# Security settings
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
X_FRAME_OPTIONS = 'DENY'
'''

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'authapi.User'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:8080",
    "http://127.0.0.1:9000",
]



# [2025-03-30]
# Author: Shivam and Rajesh
# Description: Added Amazon Credentials to authenticate
# Added only for Campaign data
"""
Amazon Ads API Configuration

This file contains credentials and endpoint URLs required to authenticate
and interact with Amazon's Advertising API using OAuth 2.0 authentication.

WARNING: Never expose these credentials in public repositories or client-side code.
Instead, store them securely using environment variables or a secrets manager.
"""

# Amazon Ads API Credentials
# These credentials are used for OAuth 2.0 authentication.
AMAZON_ADS_CLIENT_ID = "amzn1.application-oa2-client.64825a3ddf7b4ea3bd5508830526f3e5"  # Unique identifier for your application
AMAZON_ADS_CLIENT_SECRET = "amzn1.oa2-cs.v1.198e0244fd3c2a53808c18c547b18b05b898fd31e6b8bdc3872ccabf86f68145"  # Secret key for authentication
AMAZON_ADS_REFRESH_TOKEN = "Atza|IwEBIH_4WdoQbwrdefePqzV7l7nyEXPZYovRE9sHnk8HyB7fAbqvhG4mprGPH2V7U6T4T4iZJ3SAzM6egz0kIVNM-OTpHaJWC8RdG6952KbzxQRafScoHQnbILnIilCxlj4RfsTb2C5pdOVmSxG6wWEV0d4U_s2KvhhECcaI0XKydARsW5EgE7sa61jyYn8rTCkxHVw6zuT18OP0JrS-Jroh3cwQt2mO5OJLAYrC1DwS8-G5qj2oaiKJnZQRJ1nsqbLbwnO1vji8pcaB7oCe2gwwh8ezuir145_gt6dFMSkUeuYoilVOCgadVQ4kAmQ8M6e7GFCBicwx4p2iF6ZG7BFyRvv1gpzlXk956KgrK1q0Xmfxgo8LYnWLqDTeKFgw7wl2-wnD7mMV2gQXdAyrL2pVq1wyc5DVx_089GuUbiwEvQNMH5AAFtCjuSQUyvg466Hf2h9OfSFF4SXMCZPGra39knSN"  # Used to obtain new access tokens without user intervention

# OAuth 2.0 Authorization URLs
# Used to authenticate and request access tokens from Amazon's authentication server.
AMAZON_ADS_REDIRECT_URI = "https://www.amazon.com/"  # Redirect URI after user authentication
AMAZON_ADS_AUTH_URL = "https://www.amazon.com/ap/oa"  # Amazon's OAuth 2.0 authorization endpoint
AMAZON_ADS_TOKEN_URL = "https://api.amazon.com/auth/o2/token"  # Token exchange endpoint for obtaining access tokens

# Amazon Ads API Endpoint for Reporting
# This URL is used to request advertising performance reports from Amazon.
AMAZON_ADS_REPORT_URL = "https://advertising-api-eu.amazon.com/reporting/reports"  # API endpoint for fetching ad reports

# SECURITY NOTICE:
# - Store sensitive information using environment variables or a secure vault.
# - Example of fetching credentials securely:
#
#   import os
#   AMAZON_ADS_CLIENT_ID = os.getenv("AMAZON_ADS_CLIENT_ID")
#   AMAZON_ADS_CLIENT_SECRET = os.getenv("AMAZON_ADS_CLIENT_SECRET")
#   AMAZON_ADS_REFRESH_TOKEN = os.getenv("AMAZON_ADS_REFRESH_TOKEN")

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'amazon_api.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'based.amazonapis': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
