# Generated by Django 5.1.7 on 2025-04-25 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be paid', max_digits=10, verbose_name='Amount')),
                ('payment_id', models.CharField(blank=True, help_text='Unique identifier for the payment', max_length=255, null=True, unique=True, verbose_name='Payment ID')),
                ('order_id', models.CharField(help_text='Unique identifier for the order', max_length=255, unique=True, verbose_name='Order ID')),
                ('signiture', models.CharField(blank=True, help_text='Signiture for the payment', max_length=255, null=True, verbose_name='Signiture')),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed')], default='created', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
